- name: Find ab-awx-backup-worker pod for backup pruning
  kubernetes.core.k8s_info:
    kind: Pod
    kubeconfig: kubeconfiglocal
    namespace: awx
    context: "{{ abkubecontextsecondary }}"
    label_selectors:
      - app = ab-awx-backup-worker
  register: backup_podname_full2
- name: set backup_podname fact
  set_fact:
    backup_podname2: "{{ backup_podname_full2.resources[0].metadata.name }}"
- name: print
  debug:
    msg: "{{ backup_podname2 }}"
- name: Prune old backup dirs on pvc
  kubernetes.core.k8s_exec:
    namespace: awx
    kubeconfig: kubeconfiglocal
    context: "{{ abkubecontextsecondary }}"
    pod: "{{ backup_podname2 }}"
    command: '/bin/sh -c "ls -ldr /pvc/* "'
  register: command_status2
- name: Sending an e-mail
  community.general.mail:
    host: smtprelay.company.com 
    port: 25
    sender: 'no-reply-awx@company.com'
    to: 'You <you@company.com>'
    subject: "Ansible backup report for {{ abkubecontextsecondary }}"
    body: "{{ command_status2.stdout | to_nice_yaml }}"
