- name: "Remove awxbackup-{{ ansible_date_time.day }} backup if exists"
  kubernetes.core.k8s:
    kubeconfig: kubeconfiglocal
    state: absent
    validate_certs: no
    context: "{{ abkubecontext }}"
    definition:
      apiVersion: awx.ansible.com/v1beta1
      kind: AWXBackup
      metadata:
        name: "awxbackup-{{ ansible_date_time.day }}"
        namespace: awx
- name: Wait for backup to be deleted
  ansible.builtin.pause:
    minutes: 5
- name: "Create backup awxbackup-{{ ansible_date_time.day }}"
  kubernetes.core.k8s:
    kubeconfig: kubeconfiglocal
    state: present
    validate_certs: no
    context: "{{ abkubecontext }}"
    definition:
      apiVersion: awx.ansible.com/v1beta1
      kind: AWXBackup
      metadata:
        name: "awxbackup-{{ ansible_date_time.day }}"
        namespace: awx
      spec:
        deployment_name: awx
        backup_pvc: 'awx-backup-claim'
        clean_backup_on_delete: True
        backup_resource_requirements:
          limits:
            cpu: "1000m"
            memory: "4096Mi"
          requests:
            cpu: "25m"
            memory: "32Mi"
- name: Wait for backup to be created
  ansible.builtin.pause:
    minutes: 5
- name: Get our backup dir
  kubernetes.core.k8s_info:
    kubeconfig: kubeconfiglocal
    api_version: awx.ansible.com/v1beta1
    kind: AWXBackup
    context: "{{ abkubecontext }}"
    field_selectors:
      - "metadata.name=awxbackup-{{ ansible_date_time.day }}"
  register: our_awxbackup
  until: our_awxbackup.resources[0].status.backupDirectory is defined and our_awxbackup.resources[0].status.backupDirectory | length > 0
  retries: 15
  delay: 60
- name: Set backupDirectory fact
  set_fact:
    backup_dir: "{{ our_awxbackup.resources[0].status.backupDirectory }}"
- name: Print ourbackup
  debug:
    msg: "{{ backup_dir }}"
